global using System.Collections.Generic;
global using System;
global using System.Linq;
global using System.Text;
global using System.Collections;
global using System.Diagnostics;
global using System.IO;
global using SunamoStopwatch._sunamo.SunamoDictionary;
global using SunamoStopwatch._sunamo.SunamoStringSplit;
global using SunamoStopwatch._sunamo.SunamoExceptions;
global using System.Reflection;
global using System.Net;
global using System.Diagnostics.CodeAnalysis;
global using SunamoStopwatch;
global using SunamoStopwatch._sunamo;
global using SunamoStopwatch._sunamo.SunamoString;
global using ILogger = Microsoft.Extensions.Logging.ILogger;
global using Microsoft.Extensions.Logging;
global using NullLogger = Microsoft.Extensions.Logging.Abstractions.NullLogger;
