namespace SunamoStopwatch;

/// <summary>
/// Provides instance-based stopwatch functionality for measuring elapsed time of operations.
/// </summary>
public class StopwatchHelper
{
    /// <summary>
    /// Separator text used between operation name and elapsed time.
    /// </summary>
    public const string Takes = " takes ";

    /// <summary>
    /// Stores the last message generated by a stop-and-print operation.
    /// </summary>
    public string? LastMessage { get; set; }

    /// <summary>
    /// Accumulates elapsed time messages from multiple operations.
    /// </summary>
    public StringBuilder ElapsedStringBuilder { get; set; } = new();

    /// <summary>
    /// Underlying stopwatch used for time measurement.
    /// </summary>
    public Stopwatch Stopwatch { get; set; } = new();

    /// <summary>
    /// Gets the total elapsed time in milliseconds.
    /// </summary>
    public long ElapsedMilliseconds => Stopwatch.ElapsedMilliseconds;

    /// <summary>
    /// Saves the elapsed time for the specified operation and appends it to the elapsed string builder.
    /// </summary>
    /// <param name="operationName">Name of the operation being measured.</param>
    public void SaveElapsed(string operationName)
    {
        var elapsedMilliseconds = Stopwatch.ElapsedMilliseconds;
        Stopwatch.Reset();
        var message = operationName + Takes + elapsedMilliseconds + "ms";
        ElapsedStringBuilder.AppendLine(message);
    }

    #region Reset,Start,Stop

    /// <summary>
    /// Resets the stopwatch to zero.
    /// </summary>
    public void Reset()
    {
        Stopwatch.Reset();
    }

    /// <summary>
    /// Resets and starts the stopwatch.
    /// </summary>
    public void Start()
    {
        Stopwatch.Reset();
        Stopwatch.Start();
    }

    /// <summary>
    /// Stops the stopwatch, resets it, and returns the elapsed time as a string.
    /// </summary>
    /// <returns>Elapsed time in milliseconds formatted as a string.</returns>
    public string Stop()
    {
        var result = Stopwatch.ElapsedMilliseconds + "ms";
        Stopwatch.Reset();
        return result;
    }

    #endregion

    #region StopAnd*

    /// <summary>
    /// Stops the stopwatch, prints the elapsed time with optional format arguments, and returns the elapsed milliseconds.
    /// </summary>
    /// <param name="operationName">Name of the operation being measured.</param>
    /// <param name="formatSuffix">Additional format string appended after the elapsed time.</param>
    /// <param name="formatArguments">Arguments for the format string.</param>
    /// <returns>Elapsed time in milliseconds.</returns>
    public long StopAndPrintElapsed(string operationName, string formatSuffix, params string[] formatArguments)
    {
        var elapsedMilliseconds = Stopwatch.ElapsedMilliseconds;
        Stopwatch.Reset();
        LastMessage = string.Format(operationName + Takes + elapsedMilliseconds + "ms" + formatSuffix, formatArguments);
        Console.WriteLine(LastMessage);
        return elapsedMilliseconds;
    }

    /// <summary>
    /// Stops the stopwatch, prints the elapsed time, and returns the elapsed milliseconds.
    /// </summary>
    /// <param name="operationName">Name of the operation being measured.</param>
    /// <returns>Elapsed time in milliseconds.</returns>
    public long StopAndPrintElapsed(string operationName)
    {
        return StopAndPrintElapsed(operationName, string.Empty);
    }

    #endregion
}
