namespace SunamoStopwatch;

/// <summary>
/// Provides static stopwatch functionality for measuring elapsed time of operations.
/// </summary>
public static class StopwatchStatic
{
    /// <summary>
    /// Separator text used between operation name and elapsed time.
    /// </summary>
    public const string Takes = " takes ";

    /// <summary>
    /// Accumulates elapsed time messages from multiple operations.
    /// </summary>
    public static StringBuilder ElapsedStringBuilder { get; set; } = new();

    private static readonly StopwatchHelper stopwatchHelper = new();

    /// <summary>
    /// Gets the total elapsed time in milliseconds.
    /// </summary>
    public static long ElapsedMilliseconds => stopwatchHelper.ElapsedMilliseconds;

    /// <summary>
    /// Gets the last message generated by a stop-and-print operation.
    /// </summary>
    public static string? LastMessage => stopwatchHelper.LastMessage;

    /// <summary>
    /// Prints elapsed time for the operation and restarts the stopwatch.
    /// </summary>
    /// <param name="operationName">Name of the operation being measured.</param>
    public static void PrintElapsedAndContinue(string operationName)
    {
        StopAndPrintElapsed(operationName);
        Start();
    }

    /// <summary>
    /// Saves the elapsed time for the specified operation and appends it to the elapsed string builder.
    /// </summary>
    /// <param name="operationName">Name of the operation being measured.</param>
    public static void SaveElapsed(string operationName)
    {
        var elapsedMilliseconds = stopwatchHelper.Stopwatch.ElapsedMilliseconds;
        stopwatchHelper.Reset();
        var message = operationName + StopwatchHelper.Takes + elapsedMilliseconds + "ms";
        ElapsedStringBuilder.AppendLine(message);
    }

    /// <summary>
    /// Calculates the average elapsed time for each unique operation from a list of timing records.
    /// </summary>
    /// <param name="list">List of timing records in the format "operationName takes Nms".</param>
    /// <param name="averageCalculator">Function that calculates average from a list of integers and returns a formatted string.</param>
    /// <returns>Formatted string with average times per operation.</returns>
    public static string CalculateAverageOfTakes(List<string> list, Func<List<int>, string> averageCalculator)
    {
        var dictionary = new Dictionary<string, List<int>>();

        foreach (var item in list)
            if (item.Contains(Takes))
            {
                var parts = SHSplit.Split(item, Takes);
                var millisecondsText = parts[1].Replace("ms", string.Empty);

                DictionaryHelper.AddOrCreate(dictionary, parts[0], int.Parse(millisecondsText));
            }

        var stringBuilder = new StringBuilder();
        foreach (var item in dictionary) stringBuilder.AppendLine(item.Key + " " + averageCalculator(item.Value) + "ms");

        return stringBuilder.ToString();
    }

    #region Reset,Start,Stop

    /// <summary>
    /// Resets and starts the stopwatch.
    /// </summary>
    public static void Start()
    {
        stopwatchHelper.Start();
    }

    /// <summary>
    /// Resets the stopwatch to zero.
    /// </summary>
    public static void Reset()
    {
        stopwatchHelper.Reset();
    }

    #endregion

    #region StopAnd*

    /// <summary>
    /// Stops the stopwatch, resets it, and returns the elapsed milliseconds.
    /// </summary>
    /// <returns>Elapsed time in milliseconds.</returns>
    public static long StopAndElapsedMilliseconds()
    {
        var elapsedMilliseconds = stopwatchHelper.Stopwatch.ElapsedMilliseconds;
        stopwatchHelper.Stopwatch.Reset();
        return elapsedMilliseconds;
    }

    /// <summary>
    /// Stops the stopwatch, prints the elapsed time, and returns the elapsed milliseconds.
    /// </summary>
    /// <param name="operationName">Name of the operation being measured.</param>
    /// <returns>Elapsed time in milliseconds.</returns>
    public static long StopAndPrintElapsed(string operationName)
    {
        return stopwatchHelper.StopAndPrintElapsed(operationName);
    }

    /// <summary>
    /// Stops the stopwatch, prints the elapsed time with optional format arguments, and returns the elapsed milliseconds.
    /// </summary>
    /// <param name="operationName">Name of the operation being measured.</param>
    /// <param name="formatSuffix">Additional format string appended after the elapsed time.</param>
    /// <param name="formatArguments">Arguments for the format string.</param>
    /// <returns>Elapsed time in milliseconds.</returns>
    public static long StopAndPrintElapsed(string operationName, string formatSuffix, params string[] formatArguments)
    {
        return stopwatchHelper.StopAndPrintElapsed(operationName, formatSuffix, formatArguments);
    }

    #endregion
}
